# sources.nix — auto-generated by CI.  URLs point at this repo's own GitHub releases.
{
  koreader = {
    version = "0.0.0";
    arm64 = {
      url = "https://github.com/OWNER/REPO/releases/download/koreader-v0.0.0/koreader-macos-arm64.7z";
      sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };
    x86_64 = {
      url = "https://github.com/OWNER/REPO/releases/download/koreader-v0.0.0/koreader-macos-x86_64.7z";
      sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };
  };
  koreader-nightly = {
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-arm64.7z";
      sha256 = "sha256-5l8HkwtceMhv3GxJaLZdocFSOxdaZWRxCA90JSrVRCg=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-x86_64.7z";
      sha256 = "sha256-VDqy4Q+pCmGQIktLOUDb6c7lVHo4cRSBzTTWvllm6bI=";
    };
  };
}
