# sources.nix — auto-generated by CI.  URLs point at this repo's own GitHub releases.
{
  koreader = {
    version = "0.0.0";
    arm64 = {
      url = "https://github.com/OWNER/REPO/releases/download/koreader-v0.0.0/koreader-macos-arm64.7z";
      sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };
    x86_64 = {
      url = "https://github.com/OWNER/REPO/releases/download/koreader-v0.0.0/koreader-macos-x86_64.7z";
      sha256 = "sha256-AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=";
    };
  };
  koreader-nightly = {
    arm64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-arm64.7z";
      sha256 = "sha256-MCcz1vgMlT+nIK5NGYwTahSppzuqX1FE4grZCr4+wtI=";
    };
    x86_64 = {
      url = "https://github.com/proItheus/homebrew-koreader-macos/releases/download/koreader-nightly/koreader-macos-x86_64.7z";
      sha256 = "sha256-dvddI7yzHn1DLmRaYSPlh9ToJcOqf67/HWe8mXpVjpU=";
    };
  };
}
